query ($category: String!){
  category(category_name: $category) {
    id
    category_name
    img_path
    title
    light{
      id
      product_name
      file_path
      price
      
    }
  }
}